### ISSUE TITLE
Integrated With Livewire

### ISSUE THREAD

**Issue by IhsanDevs** [amaelftah/laravel-trix#69]
Does this library support Livewire? If so, how to integrate it? Because this is not in the documentation.

**Comment by hugoaf** [comment]
See this example:
https://github.com/jackoftraits/laravel8-with-livewire/blob/734a1e3a13253a5fd2b0ab7dd6acf63dab51de0d/resources/views/livewire/pages.blade.php#L109-L119

**Comment by IhsanDevs** [comment]
> See this example:
> https://github.com/jackoftraits/laravel8-with-livewire/blob/734a1e3a13253a5fd2b0ab7dd6acf63dab51de0d/resources/views/livewire/pages.blade.php#L109-L119
> 

okay. thankyou for the response. I will try it
