### ISSUE TITLE
Laravel 10 upgrade breaks on Laravel-trix

### ISSUE THREAD

**Issue by JurgenThijs** [amaelftah/laravel-trix#78]
When you want to upgrade your Laravel project to Laravel 10 it gives following error

Problem 1
    - Root composer.json requires te7a-houdini/laravel-trix ^2.0.6 -> satisfiable by te7a-houdini/laravel-trix[2.0.6, 2.0.7, 2.0.8].
    - te7a-houdini/laravel-trix[2.0.6, ..., 2.0.8] require laravel/framework ~5.8.0|~6.0|~7.0|~8.0|~9.0 -> found laravel/framework[v5.8.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but it conflicts with your root composer.json require (^10.0).

**Comment by chx2** [comment]
Looks like https://github.com/amaelftah/laravel-trix/pull/77 has been opened to resolve this @amaelftah any estimate on when that can be merged?

**Comment by amaelftah** [comment]
fixed it in 2.0.9
